### ISSUE TITLE
-Werror=unused-function

### ISSUE THREAD

**Issue by simonvcodes** [DimitriPapadopoulos/openfortivpn-debian#1]
Hello, 

i found this project via https://github.com/adrienverge/openfortivpn which i tried first.
I am working with debian testing and when running make I still get the following
`  CC       src/openfortivpn-io.o \n
src/io.c:49:22: error: ‘thread_id’ defined but not used [-Werror=unused-function]
 static unsigned long thread_id()
                      ^~~~~~~~~\n
src/io.c:42:13: error: ‘lock_callback’ defined but not used [-Werror=unused-function]
 static void lock_callback(int mode, int type, char *file, int line)
             ^~~~~~~~~~~~~
cc1: all warnings being treated as errors\n
Makefile:516: die Regel für Ziel „src/openfortivpn-io.o“ scheiterte
make: *** [src/openfortivpn-io.o] Fehler 1
`
Do I have to make further changes to the debian/rules file to make debian treat the warning in a "non-error-way"? Any help is well appreciated

**Comment by DimitriPapadopoulos** [comment]
What are you trying to do here?

A Debian package is in the works elsewhere:
https://github.com/adrienverge/openfortivpn/issues/81

I wasn't very happy when someone else stepped in and took over the Debian package, bypassing Debian rules in the process and discarding all of my existing work. But then that means less work for me :-)

This is repo is obsolete. I'll discard it at some point.
